✨ Revamp site navigation
likecoin/nft-book-press pull request #180
Opened 2024-08-27 16:15 UTC by nwingt

![likecoin-nft-book-press-testnet netlify app_](https://github.com/user-attachments/assets/d7501efe-8bd2-4b89-ba8e-916efa5020db)

![likecoin-nft-book-press-testnet netlify app_(iPad Pro)](https://github.com/user-attachments/assets/6089343f-9bb3-45c3-8a28-584f632c1c25)

2024-08-28 18:51 UTC, williamchong requested changes

2024-08-28 18:51 UTC, williamchong commented on components/SiteMenu.vue
> +        <ul v-if="props.isLarge" class="flex flex-wrap gap-4">
Why 2 `props.isLarge`?

2024-08-29 00:45 UTC, nwingt commented on components/SiteMenu.vue
> +        <ul v-if="props.isLarge" class="flex flex-wrap gap-4">
Fixed

2024-08-29 03:09 UTC, williamchong approved these changes

2024-08-29 03:12 UTC, merged